# Generated by Django 5.0.3 on 2024-12-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_alter_servicetype_schema_fields_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='services_offered',
            field=models.ManyToManyField(related_name='vendors', to='vendors.servicetype'),
        ),
    ]
